#!/usr/bin/python
# scons script for the Arduino sketch
import re

from arduino_build import ArduinoBuildContext
import signal_generator_board


Import('SOFTWARE_VERSION')
Import('sketch_build_root')

context = ArduinoBuildContext(ARGUMENTS, build_root=sketch_build_root)
arduino_hex = context.build(extra_sources=signal_generator_board.get_sources(),
                            register_upload=True,
                            env_dict={'CPPPATH':
                                      signal_generator_board.get_includes(),
                                      'CPPDEFINES': {'___SOFTWARE_VERSION___':
                                      '\\"%s\\"' % SOFTWARE_VERSION}})

Export('arduino_hex')
